### ISSUE TITLE
Why pyrinex can't read nav files correctly？

### ISSUE THREAD

**Issue by ChenDuxiunotset** [scivision/pyrinex#11]
I got questions when I use pyrinex to read nav files.The error  is followed down and I want to know how I can solve the problem.
*******************************************************************************************************
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.1\helpers\pydev\pydevd.py", line 1668, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.1\helpers\pydev\pydevd.py", line 1662, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.1\helpers\pydev\pydevd.py", line 1072, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/lenovo/Desktop/毕设/程序/dual_frequency/rinex.py", line 2, in <module>
    navdata = pyrinex.rinexnav('ntus0010.18n')
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\pyrinex\__init__.py", line 71, in rinexnav
    darr = np.genfromtxt(BytesIO(raws.encode('ascii')))
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\lib\npyio.py", line 2019, in genfromtxt
    raise ValueError(errmsg)
ValueError: Some errors were detected !

**Comment by scivision** [comment]
This would typically mean there were character(s) in the file that Numpy.loadtxt() could not process. Non-numeric characters where numbers were expected

**Comment by ChenDuxiunotset** [comment]
Thank you!What can I do to solve the problem?I try several navigation messages,they can't  be read too

**Comment by ChenDuxiunotset** [comment]
Thank you!What can I do to solve the problem?I try several navigation messages,they can't  be read too

**Comment by scivision** [comment]
Are you able to share one of the files that doesn't work?

**Comment by ChenDuxiunotset** [comment]
I have sent one of the files by e-mail

**Comment by scivision** [comment]
Hello, I unfortunately didn't seem to get the email. I did check spam. Did you send it to 
outlook.com
scivision.co
email or?

**Comment by ChenDuxiunotset** [comment]
Can you give the e-mail address to me?I will send the file to you

**Comment by scivision** [comment]
michael@scivision.co

**Comment by ChenDuxiunotset** [comment]
I have sent again.Did you receive the file？

**Comment by scivision** [comment]
fix is under testing now.

**Comment by scivision** [comment]
Fix has been pushed to "develop" branch, soon to be merged to "master"

**Comment by ChenDuxiunotset** [comment]
Thank you for the update.However，the rinexobs has problems，like this：
Traceback (most recent call last):
  File "C:/Users/lenovo/Desktop/dual_frequency/rinex.py", line 6, in <module>
    obsdata = pyrinex.rinexobs('wuh20010.18o')
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\pyrinex\__init__.py", line 53, in rinexobs
    data = _scan(f)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\pyrinex\__init__.py", line 112, in _scan
    toffset = float(l[68:80])
ValueError: could not convert string to float:

**Comment by scivision** [comment]
Yes I'm working on Rinex 3 OBS in "develop" branch. I'm restructuring the code to reflect differences between Rinex 2 and 3 for most efficient block processing. 
Hopefully today/tomorrow it will be ready.

**Comment by scivision** [comment]
in "develop" branch, RINEX 3 OBS and NAV are working, give it a try
```
git checkout develop
git pull
```

**Comment by ChenDuxiunotset** [comment]
Hello，I have take the newest version a try，but there are still some questions.
Pyrenix.renixobs still make error in read 'wuh20010.18o'.I will send the obs file to you.
I hope you can promote the function of pyrenix.Thank you for your attention and time.
***********************************************************************************************
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.1\helpers\pydev\pydevd.py", line 1668, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.1\helpers\pydev\pydevd.py", line 1662, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.1\helpers\pydev\pydevd.py", line 1072, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/lenovo/Desktop/dual_frequency/rinex.py", line 6, in <module>
    obsdata = pr.rinexobs('wuh20010.18o')
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\pyrinex\__init__.py", line 75, in rinexobs
    obs = _scan2(fn, verbose)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\pyrinex\rinex2.py", line 183, in _scan2
    data = xarray.Dataset(dsf,coords={'time':[time],'sv':sv}, attrs={'toffset':toffset})
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\xarray\core\dataset.py", line 364, in __init__
    self._set_init_vars_and_dims(data_vars, coords, compat)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\xarray\core\dataset.py", line 382, in _set_init_vars_and_dims
    data_vars, coords, compat=compat)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\xarray\core\merge.py", line 363, in merge_data_and_coords
    return merge_core(objs, compat, join, explicit_coords=explicit_coords)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\xarray\core\merge.py", line 433, in merge_core
    dims = calculate_dimensions(variables)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\xarray\core\dataset.py", line 108, in calculate_dimensions
    (dim, size, k, dims[dim], last_used[dim]))
ValueError: conflicting sizes for dimension 'sv': length 16 on 'sv' and length 28 on 'C1'

**Comment by scivision** [comment]
Thank you, the fix is in "develop" branch, this is a large Rinex file, but now it works too.

git checkout develop
git pull

**Comment by scivision** [comment]
Note the "-o" command line option allows writing to NetCDF4, for orders of magnitude faster processing of the GPS data by other programs.

**Comment by scivision** [comment]
These fixes are more are now in master branch, and from PyPi as PyRinex version 1.2.5
